version: "3.7"
services:
  server:
    env_file:
      - .env
    image: "node:14.15.1"
    working_dir: /app
    command: bash -c "yarn && yarn start"
    restart: always
    depends_on:
      - db
    ports:
      - "${API_PORT:-5000}:${API_PORT:-5000}"
    environment:
      API_PORT: "${API_PORT:-5000}"
      DATABASE_HOST: mongodb
      DATABASE_PORT: 27017
      DATABASE_NAME: twidb
      MONGO_ROOT_USERNAME: admin
      MONGO_ROOT_PASSWORD: adminpwd
    volumes:
      - ./back:/app
      - /app/node_modules
    networks:
      - db_net
  db:
    image: "mongo:4.2.3"
    container_name: mongodb
    restart: always
    ports:
      - "${DB_PORT:-27017}:${DB_PORT:-27017}"
    volumes:
      - ./db:/data/db
    networks:
      - db_net
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpwd
      MONGO_INITDB_DATABASE: "twidb"
      MONGODB_USER: "twiuser"
      MONGODB_DATABASE: "twidb"
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: adminpwd
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
    ports:
      - "8082:8081"
    networks:
      - db_net
    depends_on:
      - db
networks:
  db_net:
